# Base configs
baseurl: "https://tly311.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Thu Ly"
subtitle: "My photography collection"
author: "Thu Ly"
header:
 title: "Photography"
 subtitle: "by Thu Ly"
footer:
 name: "Hey there, my name is Thu"
 bio: "I am a consultant learning film photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/one_thu_three"
  github: "https://www.github.com/tly311"
